### ISSUE TITLE
Build error: Service account object must contain a string "project_id" property

### ISSUE THREAD

**Issue by RachelHow** [leerob/fastfeedback#23]
Hi @leerob! I love your React 2025 course 👍 

Just a tiny issue that I ran into and failed to find solutions online. I tried deploying my code to Vercel and during build time, this is the error:

```
type: 'FirebaseAppError',
errorInfo: {
  code: 'app/invalid-credential',
  message: 'Service account object must contain a string "project_id" property.'
},
```

In my `firebase.js` and `firebase-admin.js`, I have set the `projectId` and `project_id` respectively.
I have also included the environment variables in `.env`, `.env.local` and Vercel environment variable settings.

**Comment by leerob** [comment]
Are those values set to environment variables? If so, you'll need to ensure you add the environment variables inside your Vercel project as well – for both the preview and production environments.

**Comment by RachelHow** [comment]
Hi @leerob , yes they are set to env settings in Vercel project :) On production, preview and development environments.

**Comment by leerob** [comment]
Does yours look like this? 

- https://github.com/leerob/fastfeedback/blob/master/lib/firebase.js#L10
- https://github.com/leerob/fastfeedback/blob/master/lib/firebase-admin.js#L8

Is it prefixed with NEXT_PUBLIC_?

**Comment by RachelHow** [comment]
Hey @leerob, I replaced all the API keys on Vercel again to make sure there's no mistake.

After that, I ran into an error: `Error: Failed to parse private key: Error: Invalid PEM formatted message.`
To fix it, I added this to `firebase-admin.js`:
`private_key: process.env.FIREBASE_PRIVATE_KEY.replace(/\\n/g, '\n'),`

And it's solved! Thank you so much. 👍

**Comment by simonh1000** [comment]
I have the same error, but using sveltekit. My env variable on vercel is called `VITE_FIREBASE_SERVICE_ACCOUNT_KEY`
I have this code 
```
import { env } from '$env/dynamic/private';
const serviceAccount = JSON.parse(env.VITE_FIREBASE_SERVICE_ACCOUNT_KEY || '{}');
```
and I get `FirebaseAppError: Service account object must contain a string "project_id" property.`

I would think the issue is that it is not finding the key and thus parsing `{}` instead
