### ISSUE TITLE
Starting with Firebase 7.24.0 `user.xa` doesn't return a valid token anymore.

### ISSUE THREAD

**Issue by fenske** [leerob/fastfeedback#25]
### Issue Description
I was updating the dependencies in my app which follows a similar design as Fast Feedback. And when I bumped up the Firebase Lib to a new version (7.17.1 -> 7.24.0), all `auth.verifyIdToken(req.headers.token)` calls on the server-side started failing with the following error:
```
Decoding Firebase ID token failed. Make sure you passed the entire string JWT which represents an ID token
```

After troubleshooting it I found out that the token is fetched via `user.xa` client-side which doesn't work any longer.

Fast Feedback does the same on [this line](https://github.com/leerob/fastfeedback/blob/master/lib/auth.js#L122). I didn't verify it but chances are it's exposed to the same problem.

### Fix
The solution that worked for me was fetching the token in the following way instead:
```
const idTokenResult = await user.getIdTokenResult();
const idToken = idTokenResult.token;
```

**Comment by Regisnut** [comment]
Hi fenske, I had kind of same issue, the token retrieved was false, 
In Auth.js, I decided to change user.xa by user.ya as seeing the object, it retrieved the token for ya, as below
`const formatUser = async (user) => {
  return {
    uid: user.uid,
    email: user.email,
    name: user.displayName ?user.displayName : "non renseigné",
    **token: user.ya**,
    provider: user.providerData[0].providerId,
    photoUrl: user.photoURL,
    // stripeRole: await getStripeRole()
  };
};`

**Comment by joe-bell** [comment]
This fix works great, thanks @fenske

**Comment by Angelfire** [comment]
I tried to use `const { token } = await user.getIdTokenResult();` but I got the following error:

> FirebaseError: Function DocumentReference.set() called with invalid data. Unsupported field value: undefined (found in field uid in document

I had to use `token: user.ya`

I'm using:
```
"firebase": "^8.2.0",
"firebase-admin": "^9.4.2",
```

**Comment by Hamaad-Siddiqui** [comment]
The simplest solution is just to use : `token: user.ya`
Instead of :  `token: user.xa`

I am using :
```
"firebase": "^8.2.1",
"firebase-admin": "^9.4.2",
```
You can do this  if your using Firebase v8 or greater otherwise you can use  @fenske's solution :)

**Comment by leerob** [comment]
Fixed! https://github.com/leerob/fastfeedback/pull/31
