### ISSUE TITLE
Cannot read property `map` of undefined; Deployment error, Working good in local environment

### ISSUE THREAD

**Issue by manuarora700** [leerob/fastfeedback#26]
Hey, @leerob! Great course, absolutely loving it.

I was facing an issue in Vercel deployment. I've coded along till stream:5 where we setup the feedback page with getStaticPaths() and getStaticProps() methods, The app is running absolutely fine in the local environment. However, it is giving errors on vVercel deployment.

`
22:11:18.362 | > Build error occurred
-- | --
22:11:18.363 | TypeError: Cannot read property 'map' of undefined
22:11:18.364 | at getStaticPaths (/vercel/workpath0/.next/serverless/pages/p/[siteId].js:198:23)
22:11:18.364 | at processTicksAndRejections (internal/process/task_queues.js:97:5)
22:11:18.364 | at async buildStaticPaths (/vercel/workpath0/node_modules/next/dist/build/utils.js:17:80)
22:11:18.364 | at async Object.isPageStatic (/vercel/workpath0/node_modules/next/dist/build/utils.js:24:549) {
22:11:18.364 | type: 'TypeError'
22:11:18.364 | }
22:11:18.388 | error Command failed with exit code 1.
22:11:18.389 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
22:11:18.398 | Error: Command "yarn run build" exited with 1
22:11:20.354 | Done with "package.json"
`

I have triple checked everything and since it is working correctly in the local environment, is getStaticPaths() an issue here?

**Comment by leerob** [comment]
Have you added the environment variables to preview/production inside Vercel? 

Based on that error, inside `pages/p/[siteId].js` you are failing to fetch all the sites, thus it's `undefined` when trying to `map()` over the array.

**Comment by manuarora700** [comment]
Hey @leerob, Thank you so much for pointing me in the right direction.

The private key had some issues in the environment variables on Vercel,
I removed the quotes (It was working with quotes, I removed the actual `\n` with new lines earlier, but was throwing error).

Now it is correctly deployed and working.

Thank you. :D
