### ISSUE TITLE
Best practice way to get unauthenticated users auto forwarded to home page?

### ISSUE THREAD

**Issue by MyPalVikram** [leerob/fastfeedback#28]
Hi everyone. Currently, if you are not logged in and you visit /sites or /account you will see a shell of what the page is supposed to look like.

For now, what I have done is just wrap the component in { !user && <Settings/>} to make sure the user is authenticated before it loads. I also put up a "You are currently not logged in" with a button that forwards to the homepage. 

What would be the best practice way to check if the user is not validated and route them back to the homepage?

Another attempt I made was a useEffect that would check if the user is valid and if not route them back to the home page. This worked for the most part except refreshing the page would bring you back to the homepage right away and that's not a good experience.

Hoping to get pointed in the right direction, thanks!

**Comment by leerob** [comment]
> Another attempt I made was a useEffect that would check if the user is valid and if not route them back to the home page. This worked for the most part except refreshing the page would bring you back to the homepage right away and that's not a good experience.

Isn't that what you want, though? That's what I was going to suggest.

`useEffect` to check if the user exists. If no user, `Router.push('/')` back to the home page. Could also check a cookie in the `<Head />`.

**Comment by leerob** [comment]
Awesome! 🙌
