### ISSUE TITLE
Error: ./lib/firebase.js Attempted import error: 'apps' is not exported from 'firebase/app' (imported as 'firebase').

### ISSUE THREAD

**Issue by jpgotopo** [leerob/fastfeedback#29]
I am making app with Firebase (FastFeedBack de React 2025 course) and I got this error

./lib/firebase.js
Attempted import error: 'apps' is not exported from 'firebase/app' (imported as 'firebase').

**Comment by leerob** [comment]
This is likely because you're on a different version of Firebase then this repo 👍

**Comment by jpgotopo** [comment]
Where can I see the difference between the versions? In the package.json?

**Comment by leerob** [comment]
@jpgotopo Yep, you can compare the package.json in this repo with your own project!

**Comment by jpgotopo** [comment]
Thank you! I downgraded and it worked!
