### ISSUE TITLE
Should token verification strictly happen on the server side?

### ISSUE THREAD

**Issue by dingran** [leerob/fastfeedback#34]
Here we are verifying and decoding the id token on the client side

I'm thinking it's perhaps better to do it on the server side to be safe (i.e. add an api route for this)

https://github.com/leerob/fastfeedback/blob/dad9ad4c989320a661975c86553576c2593671ed/lib/auth.js#L112

**Comment by leerob** [comment]
It's okay to do this on the client-side too (it's using the Firebase client-side SDK). This is why there's client-side security rules!

We look at the JWT on the server-side too in API routes.
