### ISSUE TITLE
handling private key new line issue more robustly

### ISSUE THREAD

**Issue by dingran** [leerob/fastfeedback#35]
We can replace the `\\n` to actual new line (so ppl don't have to remember manually adding new line in vercel)

`privateKey: process.env.FIREBASE_PRIVATE_KEY.replace(/\\n/g, '\n'),`

https://github.com/leerob/fastfeedback/blob/dad9ad4c989320a661975c86553576c2593671ed/lib/firebase-admin.js#L8

**Comment by JayMGurav** [comment]
yep yep!!, this is the easiest go to for multi-line environment variables, resolved the same issue in my deployment yesterday 👍

**Comment by leerob** [comment]
Closing as I've made a new repo with updated patterns 😄 

https://github.com/leerob/fastfeedback/commit/84f076b59666a6c1690c8d7d75c35b7e9d2c9959
https://github.com/leerob/next-saas-starter

**Comment by leerob** [comment]
P.S. Vercel now shows you warnings inline when this happens as well!
