### ISSUE TITLE
Google and github authentication

### ISSUE THREAD

**Issue by ilko1999** [leerob/fastfeedback#36]
So i stumbled upon a bug in the main site.

I tried to login with github(keep in mind that my github and google accounts use the same email), i logged in successfully with my github account. Then i logged out and signed in with my google account that uses the same email as my github. I logged successfully again. The final step was to try and login with github again but i couldn`t do it. 

![image](https://user-images.githubusercontent.com/28828320/110321757-d1112980-801a-11eb-8aa3-8f29b2cac529.png)

this is the error that was logged in the console.

**Comment by Qnemes** [comment]
@ilko1999 https://firebase.google.com/docs/auth/web/google-signin#expandable-1

**Comment by leerob** [comment]
Closing as I've made a new repo with updated patterns 😄 

https://github.com/leerob/fastfeedback/commit/84f076b59666a6c1690c8d7d75c35b7e9d2c9959
https://github.com/leerob/next-saas-starter
