### ISSUE TITLE
Value for argument "value" is not a valid query constraint. Cannot use "undefined" as a Firestore value. If you want to ignore undefined values, enable `ignoreUndefinedProperties`.

### ISSUE THREAD

**Issue by jaymehta20** [leerob/fastfeedback#48]
### Was watching the stream 7: React 2025 – Authentication on API Routes (Firebase JWT)
![image](https://user-images.githubusercontent.com/23277339/133204536-256fe0b4-e27d-43aa-98a7-46ccb64b64da.png)
I can't seem to figure out this error
Error message when I open feedback page for a particular site: Value for argument "value" is not a valid query constraint. Cannot use "undefined" as a Firestore value. If you want to ignore undefined values, enable `ignoreUndefinedProperties`.

But when I hard code the uid value which is causing the error it works.
![image](https://user-images.githubusercontent.com/23277339/133204880-6c6fb169-6cef-4fcc-ba29-821e69ae27e6.png)
Now I can access the page 
![image](https://user-images.githubusercontent.com/23277339/133204946-a074eb77-bee9-44d4-8003-bcedd1cf5bb3.png)
#### Public repo: https://github.com/jaymehta20/fastfeedback

**Comment by leerob** [comment]
Somehow `uid` is not correct, it seems? Have you tried adding more logging to the value of `uid` from where it originated from?

**Comment by jaymehta20** [comment]
I think the `uid` is correct as when I hard code it, I can see the feedback page, and even when I console log it the value seems correct but when I compare that `uid` variable with authorId it says it's not a valid constraint. Not sure what's the issue here.

##### Public Repo: https://github.com/jaymehta20/fastfeedback

**Comment by leerob** [comment]
Closing as I've made a new repo with updated patterns 😄 

https://github.com/leerob/fastfeedback/commit/84f076b59666a6c1690c8d7d75c35b7e9d2c9959
https://github.com/leerob/next-saas-starter
