### ISSUE TITLE
Developing on GitHub Codespaces

### ISSUE THREAD

**Issue by hlwjia** [leerob/fastfeedback#52]
I've forked and set up fastfeedback on my GitHub Codespaces.

But the development experience is not good. I don't know if it's an issue with the project itself or Codespaces.

When I run fastfeedback on my local machine, it runs like a charm. 

But on Codespaces, when I do port forwarding to see site preview, the backend compiles almost every time a new page is requested. 

But sometimes, it doesn't. 

Very strange behavior. 

Any one had the same experience?

**Comment by leerob** [comment]
Closing as I've made a new repo with updated patterns 😄 

https://github.com/leerob/fastfeedback/commit/84f076b59666a6c1690c8d7d75c35b7e9d2c9959
https://github.com/leerob/next-saas-starter
